module Constants
  module ResponseKey
    AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
    USER_REGISTERED = 'USER_REGISTERED'
    RESOURCE_CREATED = 'RESOURCE_CREATED'
    OPERATION_SUCCESS = 'OPERATION_SUCCESS'
    VALIDATION_FAILED = 'VALIDATION_FAILED'
    NOT_FOUND = 'NOT_FOUND'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
  end
end
